# Generated by Django 3.2.16 on 2022-11-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.CharField(default=462839092280061, max_length=100),
        ),
    ]
